apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jupyterhub

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jupyterhub-custom-templates
    files:
      - templates/login.html
  
  - name: jupyterhub-custom-static-css
    files:
      - static/css/style.css